name: Automatic Semantic Release

on:
  push:
    branches:
      - main # Executa apenas quando há push no branch principal

jobs:
  release:
    name: Create Semantic Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # Permissão necessária para criar tags e commits no CHANGELOG.md
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Necessário para que o semantic-release leia todo o histórico de commits
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: bun install

      - name: Run Semantic Release
        run: bunx semantic-release
        env:
          # Token gerado automaticamente pelo GitHub, usado pelo semantic-release para escrever tags e releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
